service: reto-backend-starwars

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 128
  timeout: 10
  apiGateway:
    usagePlan:
      throttle:
        rateLimit: 50
        burstLimit: 100
  environment:
    DYNAMO_TABLE: ${env:DYNAMO_TABLE}
    WEATHER_API_KEY: ${env:WEATHER_API_KEY}
    JWT_SECRET: ${env:JWT_SECRET}
    CLOUDWATCH_LOG_GROUP: ${env:CLOUDWATCH_LOG_GROUP}
    CLOUDWATCH_LOG_STREAM: ${env:CLOUDWATCH_LOG_STREAM}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMO_TABLE}
        - Effect: Allow
          Action:
            - logs:PutLogEvents
            - logs:CreateLogStream
          Resource: arn:aws:logs:${self:provider.region}:*:log-group:${self:provider.environment.CLOUDWATCH_LOG_GROUP}:*
  tracing:
    lambda: true

package:
  patterns:
    - "node_modules/swagger-ui-dist/**"
    - "openapi.json"

functions:
  docs:
    handler: src/handlers/docs.handler
    tracing: Active
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: docs
          method: get
      - http:
          path: docs/{proxy+}
          method: get
      - http:
          path: /{asset+}
          method: get
      - http:
          path: favicon.ico
          method: get

  fusionados:
    handler: src/handlers/fusionados.handler
    tracing: Active
    memorySize: 512
    timeout: 5
    events:
      - http:
          path: fusionados
          method: get

  almacenar:
    handler: src/handlers/almacenar.handler
    tracing: PassThrough
    memorySize: 256
    timeout: 5
    events:
      - http:
          path: almacenar
          method: post

  historial:
    handler: src/handlers/historial.handler
    tracing: PassThrough
    memorySize: 256
    timeout: 5
    events:
      - http:
          path: historial
          method: get

resources:
  Resources:
    FusionadosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMO_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
