service: reto-backend-starwars

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  memorySize: 128
  timeout: 10
  environment:
    DYNAMO_TABLE: ${self:service}-${opt:stage, 'dev'}-fusionadosTable
    WEATHER_API_KEY: edcfd734b6ec4a8de3bb64b5d9d53de6
    JWT_SECRET: reto_backend_starwars_rimac_1234567890
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMO_TABLE}
  tracing:
    lambda: true

package:
  patterns:
    - "node_modules/swagger-ui-dist/**"
    - "openapi.json"

functions:
  docs:
    handler: src/handlers/docs.handler
    tracing: Active
    memorySize: 128
    timeout: 5
    events:
      - http:
          path: docs
          method: get
      - http:
          path: docs/{proxy+}
          method: get
      - http:
          path: /{asset+}
          method: get
      - http:
          path: favicon.ico
          method: get

  fusionados:
    handler: src/handlers/fusionados.handler
    tracing: Active
    memorySize: 512
    timeout: 5
    events:
      - http:
          path: fusionados
          method: get

  almacenar:
    handler: src/handlers/almacenar.handler
    tracing: PassThrough
    memorySize: 256
    timeout: 5
    events:
      - http:
          path: almacenar
          method: post

  historial:
    handler: src/handlers/historial.handler
    tracing: PassThrough
    memorySize: 256
    timeout: 5
    events:
      - http:
          path: historial
          method: get

resources:
  Resources:
    FusionadosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMO_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
